# Generated by Django 4.1.4 on 2023-03-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newid', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=225, null=True)),
                ('address_1', models.CharField(blank=True, max_length=225, null=True)),
                ('address_2', models.CharField(blank=True, max_length=225, null=True)),
                ('city', models.CharField(blank=True, max_length=225, null=True)),
                ('state', models.CharField(blank=True, max_length=225, null=True)),
                ('zipcode', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=225, null=True)),
                ('website', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
